### ISSUE TITLE
RIL ( Phone / Data Connection )

### ISSUE THREAD

**Issue by ElKowak** [ElKowak/patchrom_condor#3]
E/AndroidRuntime( 1935): FATAL EXCEPTION: main
E/AndroidRuntime( 1935): Process: com.android.phone, PID: 1935
E/AndroidRuntime( 1935): java.lang.RuntimeException: Unable to create application com.android.phone.PhoneApp: java.lang.SecurityException
E/AndroidRuntime( 1935): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
E/AndroidRuntime( 1935): 	at android.app.ActivityThread.access$1500(ActivityThread.java)
E/AndroidRuntime( 1935): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
E/AndroidRuntime( 1935): 	at android.os.Handler.dispatchMessage(Handler.java)
E/AndroidRuntime( 1935): 	at android.os.Looper.loop(Looper.java)
E/AndroidRuntime( 1935): 	at android.app.ActivityThread.main(ActivityThread.java)
E/AndroidRuntime( 1935): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1935): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1935): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
E/AndroidRuntime( 1935): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
E/AndroidRuntime( 1935): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1935): Caused by: java.lang.SecurityException
E/AndroidRuntime( 1935): 	at android.os.BinderProxy.transact(Native Method)
E/AndroidRuntime( 1935): 	at android.os.ServiceManagerProxy.addService(ServiceManagerNative.java)
E/AndroidRuntime( 1935): 	at android.os.ServiceManager.addService(ServiceManager.java)
E/AndroidRuntime( 1935): 	at com.android.phone.PhoneInterfaceManager.publish(PhoneInterfaceManager.java:315)
E/AndroidRuntime( 1935): 	at com.android.phone.PhoneInterfaceManager.<init>(PhoneInterfaceManager.java:309)
E/AndroidRuntime( 1935): 	at com.android.phone.PhoneInterfaceManager.init(PhoneInterfaceManager.java:290)
E/AndroidRuntime( 1935): 	at com.android.phone.PhoneGlobals.onCreate(PhoneGlobals.java:572)
E/AndroidRuntime( 1935): 	at com.android.phone.PhoneApp$Delegate.onCreate(PhoneApp.java:45)
E/AndroidRuntime( 1935): 	at miui.external.Application.onCreate(Application.java:181)
E/AndroidRuntime( 1935): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java)
E/AndroidRuntime( 1935): 	... 11 more

**Comment by ElKowak** [comment]
FIXED
